# x=int(input("enter weekday number (1-7"))
# if (x==1):
#     print("Monday")
# elif (x==2):
#     print("Tuesday")
# elif (x==3):
#     print("Wednesday")
# elif (x==4):
#     print("Thrusday")
# elif (x==5):
#     print("Friday")
# elif (x==6):
#     print("Saturday")
# elif (x==7):
#     print("Sunday")
# else:
#     print("enter weekday number between 1-7")


i=1
while 1<=20:
    if i%2==0:
         print(-i)
    else:
         print(i)
    i=i+1
    
    