month=int(input("enter a month"))
if month==1:
    print("jan=31 days")
elif month==2:
    print("feb=28 days")
elif month==3:
    print("march=31 days")
elif month==4:
    print("april=30 days")
elif month==5:
    print("may=31 days")
elif month==6:
    print("june=30 days")
elif month==7:
    print("july=31 days")
elif month==8:
    print("aug=31 days")
elif month==9:
    print("sep=30 days")
elif month==10:
    print("oct=31 days")
elif month==11:
    print("nov=30 days")
elif month==12:
    print("dec=31 days")
else:
    print("nothing")
    